### ISSUE TITLE
Hurdle 2 numpy version mismatch

### ISSUE THREAD

**Issue by coreyhahn** [SpectrumCollaborationChallenge/phase1-hurdles#10]
on a clean 11/1 install after running the scoring server I get
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 55, in eval
    try: self._callback()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 160, in __gr_block_handle
    ) for i in self.__out_indexes],
  File "/usr/local/lib/python2.7/dist-packages/hurdle1/tcp_server_sink.py", line 180, in work
    timed_out, items_consumed = self.write_items(in0, timeout=self.socket_timeout)
  File "/usr/local/lib/python2.7/dist-packages/hurdle1/tcp_server_sink.py", line 124, in write_items
    write_buff = self.residue + np.array(items).tobytes()
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
```

This error can be remedied with changing the offending 'tobytes' to 'tostring' .

Looks like the root problem is a numpy version issue?

**Comment by craig-pomeroy** [comment]
Are you seeing this issue in a container built by the Hurdle 2 build script? That should be pulling in numpy 1.11.2, which has the 'tobytes' method.

**Comment by coreyhahn** [comment]
yes, commit 2cb5860

**Comment by coreyhahn** [comment]
Totally rebuilt from scratch.  You must have pushed the updates while i was building last time so that the git clone on the lxc was up to date but the actual lxc build was not.

This is not an issue now.
